version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "kotlin-demo-postgres"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kotlin-demo"
    ports:
      - "5432:5432"
    restart: always
volumes:
  kotlin_demo_postgres_data:
